name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  unittest-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install coveralls mypy
    - name: Create somersault.pdx
      run: |
        export PYTHONPATH=$PYTHONPATH:$PWD
        cd examples
        python3 mksomersaultpdx.py somersault.pdx
    - name: Run unit tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$PWD
        python3 -m unittest tests/*.py
    - name: Static type checking with mypy
      run: |
        python3 -m mypy --ignore-missing-imports --python-version 3.8 odxtools tests examples
        python3 -m mypy --ignore-missing-imports --python-version 3.9 odxtools tests examples
        python3 -m mypy --ignore-missing-imports --python-version 3.10 odxtools tests examples
